## Jacobi Method

In [1]:
import numpy as np
import time 

def jacobi(A, b, x0, tol, max_iterations):
    n = len(b)
    x = x0.astype(float).copy()
    for k in range(max_iterations):
        x_new = np.zeros_like(x)
        for i in range(n):
            s = sum(A[i][j] * x[j] for j in range(n) if j != i)
            x_new[i] = (b[i] - s) / A[i][i]
        # Check for convergence
        if np.linalg.norm(x_new - x, ord=np.inf) < tol:
            return x_new, k
        x = x_new
    return x, max_iterations


## Gauss-Seidel Method

In [2]:
def gauss_seidel(A, b, x0, tol, max_iterations):
    n = len(b)
    x = x0.astype(float).copy()
    for k in range(max_iterations):
        x_new = x.copy()
        for i in range(n):
            s1 = sum(A[i][j] * x_new[j] for j in range(i)) # Using already updated values
            s2 = sum(A[i][j] * x[j] for j in range(i + 1, n)) # Using old values
            x_new[i] = (b[i] - s1 - s2) / A[i][i]
        # Check for convergence
        if np.linalg.norm(x_new - x, ord=np.inf) < tol:
            return x_new, k
        x = x_new
        print(x)
    return x, max_iterations

In [3]:
#Usage 
A = np.array([  [10, 2, 3, 0, 0],
                [2, 10, 2, 3, 0],
                [3, 2, 10, 2, 3],
                [0, 3, 2, 10, 2],
                [0, 0, 3, 2, 10]])

b = np.array([14, 22, 33, 26, 22])
x0 = np.zeros_like(b)
tol = 1e-6
max_iterations = 100

#Jacobi Method
start = time.perf_counter()

solution, iterations = jacobi(A, b, x0, tol, max_iterations)

end = time.perf_counter()
elapsed_time = end - start
print(f"JACOBI METHOD:")
print(f"Solution: {solution}")
print(f"Iterations: {iterations}")
print(f"Time: {elapsed_time:.6e} seconds")


print("\n\n\n")



#Gauss Seidel Method
start = time.perf_counter()

solution, iterations = gauss_seidel(A, b, x0, tol, max_iterations)

end = time.perf_counter()
elapsed_time = end - start

print(f"Gauss-Seidel METHOD:")
print(f"Solution: {solution}")
print(f"Iterations: {iterations}")
print(f"Time: {elapsed_time:.6e} seconds")



JACOBI METHOD:
Solution: [0.49048862 1.18840344 2.23943699 1.55203981 1.21776135]
Iterations: 44
Time: 9.400383e-03 seconds




[1.4     1.92    2.496   1.5248  1.14624]
[0.2672     1.18992    2.333024   1.5471712  1.19065856]
[0.4621088  1.17682208 2.25937114 1.55694744 1.21079917]
[0.48682424 1.18367669 2.24258815 1.55421953 1.21637965]
[0.49048822 1.18711887 2.23967196 1.55265402 1.21756761]
[0.49067464 1.18813448 2.23936963 1.55217221 1.21775467]
[0.49056222 1.18836197 2.2393981  1.55206086 1.2177684 ]
[0.49050818 1.18840049 2.23942476 1.55204122 1.21776433]
[0.49049247 1.18840419 2.23943388 1.5520391  1.21776202]
[0.490489   1.18840369 2.23943614 1.55203926 1.21776131]
Gauss-Seidel METHOD:
Solution: [0.49048842 1.18840331 2.23943657 1.55203943 1.21776114]
Iterations: 10
Time: 6.657163e-03 seconds
