## Jacobi Method

In [1]:
import numpy as np
import time 

def jacobi(A, b, x0, tol, max_iterations):
    n = len(b)
    x = x0.copy()
    for k in range(max_iterations):
        x_new = np.zeros_like(x)
        for i in range(n):
            s = sum(A[i][j] * x[j] for j in range(n) if j != i)
            x_new[i] = (b[i] - s) / A[i][i]
        # Check for convergence
        if np.linalg.norm(x_new - x, ord=np.inf) < tol:
            return x_new, k
        x = x_new
    return x, max_iterations


## Gauss Seidel Method

In [2]:
def gauss_seidel(A, b, x0, tol, max_iterations):
    n = len(b)
    x = x0.copy()
    for k in range(max_iterations):
        x_new = x.copy()
        for i in range(n):
            s1 = sum(A[i][j] * x_new[j] for j in range(i)) # Using already updated values
            s2 = sum(A[i][j] * x[j] for j in range(i + 1, n)) # Using old values
            x_new[i] = (b[i] - s1 - s2) / A[i][i]
        # Check for convergence
        if np.linalg.norm(x_new - x, ord=np.inf) < tol:
            return x_new, k
        x = x_new
        print(x)
    return x, max_iterations

In [3]:
#Usage 


A = np.array([  [0.582745, .48, .1, 0, 0],
                [0.48, 1.044129, 0.46, 0.10, 0],
                [.1, .46, 1.10431, 0.44, 0.1],
                [0, 0.1, 0.44, 0.963889, 0.42],
                [0, 0, 0.10, 0.42, 0.522565]], dtype=float)

b = np.array([1.162745, 2.084129, 2.20431, 1.923889, 1.042565], dtype=float)
x0 = np.zeros_like(b)
tol = 1e-6
max_iterations = 100

#Jacobi Method
start = time.perf_counter()

solution, iterations = jacobi(A, b, x0, tol, max_iterations)

end = time.perf_counter()
elapsed_time = end - start

print(f"JACOBI METHOD:")
print(f"Solution: {solution}")
print(f"Iterations: {iterations}")
print(f"Time: {elapsed_time:.6e} seconds")


print("\n\n\n")


#Gauss-Seidel Method
start = time.perf_counter()

solution, iterations = gauss_seidel(A, b, x0, tol, max_iterations)

end = time.perf_counter()
elapsed_time = end - start

print(f"Gauss-Seidel METHOD:")
print(f"Solution: {solution}")
print(f"Iterations: {iterations}")
print(f"Time: {elapsed_time:.6e} seconds")


JACOBI METHOD:
Solution: [0.34253948 0.34219824 0.34215212 0.34233398 0.34277892]
Iterations: 100
Time: 1.364202e-02 seconds




[1.99528953 1.07878435 1.3660478  1.26046623 0.72060778]
[0.87229188 0.87249783 0.98619581 1.1412702  0.88909884]
[1.10739082 0.94318261 0.96769761 1.06896363 0.95075353]
[1.05234294 0.98356346 0.97908845 1.03270942 0.97771224]
[1.01712704 0.99820654 0.98818169 1.01529249 0.9899706 ]
[1.0035053  1.00213061 0.99361016 1.00706598 0.99554366]
[0.99934155 1.00244106 0.99663098 1.00322643 0.99805153]
[0.99856745 1.0018338  0.99825676 1.00145453 0.99916455]
[0.99878866 1.00118556 0.99911196 1.00064641 0.9996504 ]
[0.99917586 1.00070819 0.99955373 1.00028257 0.99985829]
[0.99949325 1.0004025  0.99977847 1.00012112 0.99994505]
[0.99970648 1.00022093 0.99989127 1.00005066 0.99998009]
[0.99983668 1.00011813 0.9999472  1.00002052 0.99999361]
[0.99991176 1.00006186 0.99997462 1.00000795 0.99999847]
[0.9999534  1.00003184 0.99998793 1.00000288 1.        ]
[0.99997584 1.00

In [4]:
#Usage 

A = np.array([[1, 1], [1, 1.0001]])
b = np.array([1, 1])
x0 = np.zeros_like(b)
tol = 1e-6
max_iterations = 100

#Jacobi Method
start = time.perf_counter()

solution, iterations = jacobi(A, b, x0, tol, max_iterations)

end = time.perf_counter()
elapsed_time = end - start

print(f"JACOBI METHOD:")
print(f"Solution: {solution}")
print(f"Iterations: {iterations}")
print(f"Time: {elapsed_time:.6e} seconds")


print("\n\n\n")


#Gauss-Seidel Method
start = time.perf_counter()

solution, iterations = gauss_seidel(A, b, x0, tol, max_iterations)

end = time.perf_counter()
elapsed_time = end - start

print(f"Gauss-Seidel METHOD:")
print(f"Solution: {solution}")
print(f"Iterations: {iterations}")
print(f"Time: {elapsed_time:.6e} seconds")


JACOBI METHOD:
Solution: [1 0]
Iterations: 1
Time: 4.731175e-04 seconds




[1 0]
Gauss-Seidel METHOD:
Solution: [1 0]
Iterations: 1
Time: 5.916841e-04 seconds


In [5]:
#Usage 

A = np.array([[1, 1], [1, 1.0001]])
b = np.array([1, 1.0001])
x0 = np.zeros_like(b)
tol = 1e-6
max_iterations = 100

#Jacobi Method
start = time.perf_counter()

solution, iterations = jacobi(A, b, x0, tol, max_iterations)

end = time.perf_counter()
elapsed_time = end - start

print(f"JACOBI METHOD:")
print(f"Solution: {solution}")
print(f"Iterations: {iterations}")
print(f"Time: {elapsed_time:.6e} seconds")


print("\n\n\n")


#Gauss-Seidel Method
start = time.perf_counter()

solution, iterations = gauss_seidel(A, b, x0, tol, max_iterations)

end = time.perf_counter()
elapsed_time = end - start

print(f"Gauss-Seidel METHOD:")
print(f"Solution: {solution}")
print(f"Iterations: {iterations}")
print(f"Time: {elapsed_time:.6e} seconds")


JACOBI METHOD:
Solution: [0.         0.00498727]
Iterations: 100
Time: 3.834015e-03 seconds




[1.0000000e+00 9.9990001e-05]
[9.99900010e-01 1.99970004e-04]
[9.9980003e-01 2.9994001e-04]
[9.9970006e-01 3.9990002e-04]
[9.99600100e-01 4.99850035e-04]
[9.99500150e-01 5.99790056e-04]
[9.99400210e-01 6.99720084e-04]
[9.9930028e-01 7.9964012e-04]
[9.99200360e-01 8.99550165e-04]
[0.99910045 0.00099945]
[0.99900055 0.00109934]
[0.99890066 0.00119922]
[0.99880078 0.00129909]
[0.99870091 0.00139895]
[0.99860105 0.0014988 ]
[0.9985012  0.00159864]
[0.99840136 0.00169847]
[0.99830153 0.00179829]
[0.99820171 0.0018981 ]
[0.9981019 0.0019979]
[0.9980021  0.00209769]
[0.99790231 0.00219747]
[0.99780253 0.00229724]
[0.99770276 0.002397  ]
[0.997603   0.00249675]
[0.99750325 0.00259649]
[0.99740351 0.00269622]
[0.99730378 0.00279594]
[0.99720406 0.00289565]
[0.99710435 0.00299535]
[0.99700465 0.00309505]
[0.99690495 0.00319473]
[0.99680527 0.0032944 ]
[0.9967056  0.00339406]
[0.99660594 0.00349371]
[0